### ISSUE TITLE
Convert synchronous client call to asynchronous for CallStacking.com

### ISSUE THREAD

**Issue by Eazybright** [callstacking/callstacking-rails#1]
@aantix I saw this issue on [https://beginnerbounties.com/bounties/11](https://beginnerbounties.com/bounties/11). 
I would love to work on this.
Can we discuss further?

**Comment by PhillipUg** [comment]
Hey @aantix, i have been working as a backend rails engineer for a couple of years. I'd like to give this a go. I already have afew ideas.

**Comment by Ose-Augustine** [comment]
HI @aantix There are a couple ways to solve your asyn refactore request.
You can use plain old multiple threads or run it with Fiber.
However, Fiber once had concurrency problems. 
em-http-request would be the best approach. If this is not assigned, yet , we could discuss the best options

**Comment by JuzerShakir** [comment]
Hey @aantix! I saw your post on beginnerbounties.com. I am willing to take up the task and learn more about this interesting gem and work together to develop this gem in future.
